fix build
    Error: error building site: render: failed to render pages: ...
    ransform-error1085806758:1339:77": expected , or ) instead of : in arguments on line 1339 and column 77
        4: ...nious with legacy" (aka: sexy with leverage)